---
title: "NFL Big Data Bowl 2021 Project Paper"
author: "Ty Hammond, Blake Hammarstrom, Jaret Stickrod, Luke Spencer"
date: "November 29, 2024"
output: pdf_document
fontsize: 12pt
geometry: a4paper
header-includes: |
  \usepackage{titling}
  \newcommand{\university}{Colorado State University}
  \newcommand{\class}{STAT 445: Statistical Machine Learning}
  \newcommand{\professor}{Dr. Andee Kaplan}
  \renewcommand{\maketitle}{
    \begin{titlepage}
    \centering
    \vspace*{\fill}
    {\Huge \bfseries \thetitle}\\[2cm]
    {\Large \theauthor}\\[1cm]
    {\Large \university}\\[0.5cm]
    {\Large \class}\\[0.5cm]
    {\Large \professor}\\[2cm]
    {\large \thedate}
    \vspace*{\fill}
    \end{titlepage}
  }
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Motivation

Insert Motivation Here

## Methodology

Insert Methodology Here

## Conclusions

Insert Conclusions Here

## References

Insert References Here

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
